syntax = "proto3";

package basketballstats;

import "google/protobuf/empty.proto";

option csharp_namespace = "BasketballStats.Protos";

service PlayerService {
  rpc CreatePlayer (CreatePlayerRequest) returns (PlayerResponse);
  rpc GetPlayer (GetPlayerRequest) returns (PlayerResponse);
  rpc UpdatePlayer (UpdatePlayerRequest) returns (PlayerResponse);
  rpc DeletePlayer (DeletePlayerRequest) returns (google.protobuf.Empty);
  rpc ListPlayers (ListPlayersRequest) returns (ListPlayersResponse);
}

message Player {
  string id = 1;
  string first_name = 2;
  string last_name = 3;
  string badge_color = 4;
}

message CreatePlayerRequest {
  string first_name = 1;
  string last_name = 2;
  string badge_color = 3;
}

message GetPlayerRequest {
  string player_id = 1;
}

message UpdatePlayerRequest {
  string player_id = 1;
  string first_name = 2;
  string last_name = 3;
  string badge_color = 4;
}

message DeletePlayerRequest {
  string player_id = 1;
}

message PlayerResponse {
  Player player = 1;
}

message ListPlayersRequest {}

message ListPlayersResponse {
  repeated Player players = 1;
}
